<?php
$path_to_root = "../..";
$page_security = 'SA_SALESQUOTE';
include_once($path_to_root . "/includes/session.inc");
include_once($path_to_root . "/sales/includes/sales_db.inc");
include_once($path_to_root . "/includes/ui.inc");
include_once($path_to_root . "/includes/ui/contacts_view.inc");
require($path_to_root . '/sales/gcap/fpdf.php');

class PDF extends FPDF{

    function Header(){
        $this->SetFont('Arial','','15');
        $this->Cell(80);
        // Framed title
        $this->Image('ccima.png',5,5);
        $this->Image('logo_rentas.png',170,5);
        $this->Ln(15);
        // Line break
        
    }

}

function dec($letra){
    $decoded = utf8_decode($letra);
    return $decoded;
}

$id = $_REQUEST['PARAM_0'];
//service order
$sql = "SELECT so.*, cu.name, sd.description  
        FROM 1_sales_orders so INNER JOIN 1_debtors_master cu ON so.debtor_no = cu.debtor_no  
        INNER JOIN 1_sales_order_details sd ON sd.order_no = so.order_no " .
       " WHERE so.trans_type = 30 AND sd.trans_type = 30 AND so.order_no = " . db_escape($id);

$result = db_query($sql);
$row = db_fetch($result);
//inventory item
$sql = "select sm.* 
from 1_sales_order_details sd
inner join 1_stock_master sm on sd.stk_code = sm.stock_id
where sd.order_no = ".db_escape($row["order_no"])." and sd.trans_type = ".db_escape($row["trans_type"]);
$dbInventory = db_query($sql);
$invData = db_fetch($dbInventory);
$pagare = price_format($invData["pagare"]);
$pagareTexto = strtoupper(price_in_words($invData["pagare"]));
//contact data
$sql = "select pe.* FROM
1_crm_persons pe 
INNER JOIN 1_crm_contacts co on co.person_id = pe.id
WHERE co.type = 'customer' AND action='fiador' 
AND co.entity_id = " . db_escape($row['debtor_no']);
$result = db_query($sql);
$fiador = db_fetch($result);
//----------------
$sql = "select pe.* FROM
1_crm_persons pe 
INNER JOIN 1_crm_contacts co on co.person_id = pe.id
WHERE co.type = 'customer' AND action='delivery' 
AND co.entity_id = " . db_escape($row['debtor_no']);
$result = db_query($sql);
$contacto = db_fetch($result);

$sectionOne = utf8_decode(sprintf("CONDICIONES BAJO LAS CUALES ARRIENDA LA PERSONA MORAL DENOMINADA GRUPO CIMMA S.A. DE C.V. POR CONDUCTO DE SU REPRESENTANTE LEGAL ING. RICARDO MEDINA ROJAS, A QUIEN EN LO SUCESIVO SE LE DENOMINARÁ (EL ARRENDADOR), Y EL  C. %s %s EN REPRESENTACION DE %s A QUIEN EN LO SUCESIVO SE LE DENOMINARA (EL ARRENDATARIO), LOS QUE SE SUJETAN A LAS SIGUIENTES:", strtoupper($contacto["name"]), strtoupper($contacto["name2"]), strtoupper($row["name"]))); 

$sectionTwo = sprintf("A)	DECLARA EL ARRENDADOR. SER UNA PERSONA MORAL DEBIDAMENTE CONSTITUIDA CONFORME A LAS LEYES DEL PAIS,  AL CORRIENTE EN SUS OBLIGACIONES FISCALES, CON DOMICILIO UBICADO EN CARRETERA: QRO SAN LUIS POTOSI K.M. 17.5, LA CRUZ STA. ROSA JAUREGUI, QUERETARO, QRO.

B)	EL ARRENDATARIO, SER DE NACIONALIDAD MEXICANA MAYOR DE EDAD, CON DOMICILIO UBICADO EN %s, DEDICADO A LAS ACTIVIDADES NO COMERCIALES.
 
C)	AMBAS PARTES DECLARAN CONOCER EL BIEN MUEBLE OBJETO DE ARRENDAMIENTO Y ESTAR DE ACUERDO EL PRECIO QUE HAN PACTADO.

D)	AMBAS PARTES DECLARAN QUE ESTE CONTRATO TIENE UN OBJETO MERAMENTE CIVIL, INDEPENDIENTEMENTE DE SUS ACTIVIDADES PREPONDERANTES QUE DESEMPEÑEN DE FORMA COTIDIANA Y LA FORMA LEGAL EN QUE CADA UNA FUE CREADA.
", $contacto["address"]);

$pdf = new PDF();
$pdf->AddPage();
$pdf->SetFont('Arial','','8');
$pdf->Cell(190,5,'CONTRATO DE ARRENDAMIENTO',1,0,'C');
$pdf->Ln(10);
$pdf->SetFont('Arial','','7');
$pdf->MultiCell(190,4,$sectionOne);
$pdf->Ln();
$pdf->Cell(190,5,'DECLARACIONES',0,0,'C');
$pdf->Ln();
$pdf->MultiCell(190,4,$sectionTwo);
$pdf->Ln();
$pdf->SetFont('Arial','','8');
$pdf->Cell(190,5,'CLAUSULAS',1,0,'C');
$pdf->Ln();
$pdf->SetFont('Arial','','7');
$palabras = price_in_words($row['total']);
$sectionThree = utf8_decode(sprintf("P R I M E R A.- OBJETO EL ARRENDADOR DA EN ARRENDAMIENTO Y EL ARRENDATARIO RECIBE EL BIEN MUEBLE CONSISTENTE EN %s
    
S E G U N D A.- PRECIO LOS CONTRATANTES HAN PACTADO, QUE EL ARRENDATARIO DEBERA PAGAR AL ARRENDADOR LA CANTIDAD POR CONCEPTO DE RENTA LA CANTIDAD DE $ %s (%s) MAS IVA POR CONCEPTO DE RENTA DE LA MAQUINA POR DIA, QUE SE PAGARAN POR ANTICIPADO EN EL DOMICILIO DEL ARRENDADOR.", $row["description"], price_format($row["total"]), strtoupper($palabras)));
$pdf->MultiCell(190,4,$sectionThree);
$pdf->Ln();
$pickHour = new DateTime($row["fin_obra"]);
$sectionFour = utf8_decode(sprintf("T E R C E R A.- VIGENCIA LA RENTA DEL EQUIPO OBJETO DE ARRENDAMIENTO SE VERIFICARA DEL %s, A PARTIR DE LAS 08:30 HORAS, HASTA EL %s HASTA LAS %s HORAS EN EL CASO DE FALTA DE PAGO PUNTUAL DE CUALQUIERA LAS OBLIGACIONES DINERARIAS A CARGO DE EL  ARRENDATARIO, ESTE SE OBLIGA A PAGAR INTERESES MORATORIOS A RAZON DEL 5 POR CIENTO MENSUAL SOBRE EL VALOR DE LA RENTA, QUE SE CALCULARAN  POR DIA COMPLETO O FRACCION DE DIA POR EL TIEMPO DE MORA HASTA EL PAGO TOTAL. LOS INTERESES MORATORIOS SERÁN PREFERENTES AL MONTO DE LOS ABONOS VENCIDOS., COMENZANDO POR EL DE LA FECHA MAS ATRASADA Y SIGUIENDO EN EL ORDEN DE SUS  VENCIMIENTOS HASTA QUE EL ARRENDATARIO  SE PONGA AL CORRIENTE.

C U A R T A.- LUGAR,  LAS PARTES ACUERDAN QUE EL BIEN DADO EN ARRENDAMIENTO  SE ENCUENTRA EN EL PATIO DEL DOMICILIO DEL ARREDADOR Y ESTARA EN ARREDAMIENTO EN EL DOMICILIO UBICADO %s, QUERETARO QRO.. HASTA LA VIGENCIA DEL PRESENTE CONTRATO, CONFORME A LA COTIZACION Y ORDEN DE SERVICIO SUSCRITAS PARA LA CELEBRACION DE ESTE INSTRUMENTO JURIDICO, LAS CUALES SE ANEXAN DE FORMA INTEGRAL.", getSimpleDateString($row["ord_date"]),getSimpleDateString($row["delivery_date"]),date_format($pickHour, "H:i"), strtoupper($row["delivery_address"])));
$pdf->MultiCell(190,4,strtoupper($sectionFour));
$pdf->Ln();
$sectionFive = utf8_decode(sprintf("Q U I N T A.- RESPONSABILIDAD EL ARRENDATARIO ES RESPONSABLE DE LOS DAÑOS OCASIONADOS AL EQUIPO OBJETO DE ARRENDAMIENTO, DESDE SU TRASLADO Y MANIOBRAS QUE SE REALICEN PARA CUMPLIR SU OBJETIVO O QUE SEAN CAUSADOS A TERCEROS.

S E X T A.- SEGUROS PARA EL CASO DE QUE EL EQUIPO OBJETO DE ARRENDAMIENTO TRASLADE MAQUINARIA O EQUIPO DE CUALQUIER INDOLE PROPIEDAD DEL ARRENDATARIO, ESTE SE OBLIGA A CONTRATAR SEGUROS A SU COSTA PARA SALVAGUARDAR LOS RESULTADOS O PARA RESPONDER POR DAÑOS A TERCEROS CIVILES PATRIMONIALES DE CUALQUIER INDOLE.

S E P T I M A.-  EN CASO DE QUE EL EQUIPO SE PIERDA O SEA ROBADO, EMBARGADO, SECUESTRADO, DESTRUIDO O DAÑADO DURANTE EL SERVICIO, DE TAL MODO QUE SEA IMPOSIBLE SU RECUPERACIÓN Y/O REPARACIÓN DE ACUERDO A DICTAMEN EMITIDO POR UN PERITO PROFESIONAL EN LA MATERIA DENTRO DE LOS 15 DÍAS SIGUIENTES A LA FECHA DEL SUCESO, EL ARRENDATARIO SE OBLIGA A PAGAR EXPRESAMENTE A GRUPO CCIMA S.A. DE C.V., UNA SUMA EQUIVALENTE AL VALOR ESTABLECIDO DE %s (%s) POR LA GRÚA.

O C T A V A.- EL SUMINISTRO DE ENERGÍA Y/O GASOLINA SERÁ PROPORCIONADO POR EL CLIENTE, DURANTE LA VIGENCIA DEL PRESENTE CONTRATO.

N O V E N A.- EL EQUIPÓ SE RENTA COMO LO RECIBE EL ARRENDATARIO Y ASI SE OBLIGA A ENTREGARLO, EL ARRENDADOR NO ASUME RESPONSABILIDAD POR NINGUNA ASESORÍA TÉCNICA O RESULTADOS OBTENIDOS AHÍ. SI EL EQUIPO FALLA PARA OPERAR COMO ESTÁ DISEÑADO EL ARRENDADOR., HARÁ SU MEJOR ESFUERZO PARA REPARARLO O REEMPLAZARLO, LAS GARANTÍAS IMPLÍCITAS INCLUYENDO COMERCIALIZACIÓN Y PROPIEDAD PARA UN PROPÓSITO PARTICULAR ESTÁN EXCLUIDAS. EN NINGÚN CASO GRUPO CCIMA S.A. DE C.V. ES RESPONSABLE POR DAÑOS INCIDENTALES O CONSECUENCIALES. GRUPO CCIMA S.A. DE C.V. PUEDE CANCELAR O DEMORAR LA RENTA SIN RESPONSABILIDAD CASO FORTUITO O FUERZA MAYOR DEBIDAMENTE JUSTIFICADA, QUE IMPIDA LA RENTA.

D E C I M A.- QUEDA EXPRESAMENTE PROHIBIDO AL ARRENDATARIO SUBARRENDAR  O TRASPASAR EL TODO O PARTE DEL BIEN MUEBLE OBJETO DE ARRENDAMIENTO Y DE ESTE CONTRATO, SI ESTE FUERA EL CASO,  SERA CAUSAL DE RESCISION Y SE DEMANDARA ANTE EL JUEZ COMPETENTE.


D E C I M A P R I M E R A. SE CONSTITUYE COMO FIADOR EL  SR. %s %s QUIEN EN ESTE MOMENTO Y DURANTE LA VIGENCIA DEL CONTRATO RENUNCIA EL DERECHO DE ORDEN Y EXCUSIÓN Y PODRA SER REQUERIDO DEL PAGO SIN NECESIDAD DE REQUERIR EN PRIMER LUGAR A LOS ARRENDATARIO, FIRMA AL CALCE EN SEÑAL DE SU ACEPTACIÓN, Y SEÑALA COMO DOMICILIO PARA TODO TIPO DE REQUERIMIENTOS Y NOTIFICACIONES EL UBICADO EN %s.

D E C I M A   S E G U N D A.- LAS PARTES CONVIENEN QUE PARA EL CASO DE EJECUCION E INTERPRETACION DEL CONTRATO EN CASO DE CONTROVERSIA SE SOMETEN A LA JURISDICCION  DE LOS TRIBUNALES CIVILES DEL ESTADO DE QUERETARO Y A LAS LEYES CIVILES SUSTANTIVAS Y ADJETIVAS VIGENTES, RENUNCIANDO AL FUERO QUIE LES PUDIESE CORRESPONDER EN LO FUTURO EN RAZON DE SU DOMICILIO, O CALIDAD CORPORATIVA.

FIRMAN LOS QUE EN EL MISMO INTERVIENEN AL NO EXISTIR DOLO, ERROR, VIOLENCIA FISICA O MORAL O CUALQUIER VICIO DE LA VOLUNTAD, AL CALCE, LOS QUE EN ESTE ACTO INTERVIENEN. %s.

EN CASO DE QUE EL OPERADOR ASIGNADO AL SERVICIO CONSIDERE QUE LA MANIOBRA PONGA EN RIESGO LA INTEGRIDAD FISICA PROPIA Y DE LA UNIDAD, PODRÁ DECIDIR NO REALIZAR EL SERVICIO SIN RESPONSABILIDAD A GRUPO CCIMA.",$pagare, $pagareTexto, strtoupper($fiador["name"]), strtoupper($fiador["name2"]), 
strtoupper($fiador["address"]), strtoupper(getDateString($row["ord_date"]))));
$pdf->MultiCell(190,4,$sectionFive);
$pdf->Ln(30);
$pdf->Cell(60, 0, 'REPRESENTANTE LEGAL DE GRUPO CCIMA',0,0,'C');
$pdf->Cell(70, 0, 'ARRENDADOR',0,0,'C');
$pdf->Cell(60, 0, 'FIADOR',0,0,'C');
$pdf->Ln(30);
$pdf->Cell(59, 0, '',1,0,'C');
$pdf->Cell(1, 0, '',0,0,'C');
$pdf->Cell(69, 0, '',1,0,'C');
$pdf->Cell(1, 0, '',0,0,'C');
$pdf->Cell(59, 0, '',1,0,'C');

$pdf->SetY(-24);
$pdf->Cell(190,0,'Carretera: QRO - SAN LUIS POTOSI K.M. 17.5, La cruz Sta. Rosa Jauregui, Queretaro, Qro.',0,0,'C');
$pdf->Ln(3);
$pdf->Cell(190,0,'Tels: (442) 291 22 23 y 291 23 24',0,0,'C');
$pdf->Output();
?>