<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  1 => 
  array (
    'name' => 'Requisitions',
    'package' => 'requisitions',
    'version' => '2.3.13-2',
    'type' => 'extension',
    'active' => 1,
    'path' => 'modules/requisitions',
  ),
);
?>